"""initial_migration

Revision ID: 6577b5f961a0
Revises: 
Create Date: 2026-01-10 01:06:42.685853

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6577b5f961a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('unit_of_measure', sa.Enum('MBPS', 'GBPS', 'GB', 'TB', 'GHZ', 'VOLT', 'WATT', 'METER', 'NONE', 'PERCENT', 'SECONDS', 'MINUTES', 'HOURS', 'DAYS', 'MONTHS', 'YEARS', 'UNIT', name='unitofmeasure'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characteristics_name'), 'characteristics', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characteristics_name'), table_name='characteristics')
    op.drop_table('characteristics')
    # ### end Alembic commands ###
